### ISSUE TITLE
Lightning Talk A3: GraphQL

### ISSUE THREAD

**Issue by ccyccyccy** [nus-cs3281/2020#11]
Slides: [lightningTalk.pptx](https://github.com/nus-cs3281/2020/files/4198070/lightningTalk.pptx)

### WIIFY
- Better frontend and backend integration
- Earn more money

### Key Points
- GraphQL can help improve performance
- GraphQL makes code less complex.
- Great community support and confidence for GraphQL

### Impact
- Know: What is GraphQL and how it can benefit you
- Believe: That GraphQL can provide better performance for your applications
- Do: Try out GraphQL for your projects

**Comment by damithc** [comment]
> ### Key Points
> * Problems of rest
> * What is GraphQL
> * Benefits of GraphQL

These are topics, not points.

**Comment by ccyccyccy** [comment]
> > ### Key Points
> > 
> > * Problems of rest
> > * What is GraphQL
> > * Benefits of GraphQL
> 
> These are topics, not points.

Fixed.
