### ISSUE TITLE
Lightning Talk A3: Microservices

### ISSUE THREAD

**Issue by jamessspanggg** [nus-cs3281/2020#23]
## Summary

This talk aims to introduce the Microservices architecture and its advantages and disadvantages over the traditional Monolithic architecture.

## WIIFY

1. A lot of big companies are currently using Microservices architecture, and chances are you will be working with a Microservices project in the future.

## Key points

1. Microservices are highly scalable
2. Microservices are fault isolated
3. Microservices are language independent
4. Microservices can be developed, tested and deployed in isolation

## Impact

1. Understand more about Microservices and know when to use/not use.

[Link to pptx](https://drive.google.com/open?id=152_EvcCLzBJFayqPWhLXKJ2Npbr9egvO)

**Comment by damithc** [comment]
Can upload a pptx or ppt? This one looks like a keynote file.

> [](https://drive.google.com/open?id=1jYbaRjaVyLo0DHVGIrx7ERDz2cq-cu2j)

**Comment by jamessspanggg** [comment]
> Can upload a pptx or ppt? This one looks like a keynote file.

Updated the file link.
