### ISSUE TITLE
Lighning Talk Round A: .dotfiles management

### ISSUE THREAD

**Issue by tiuweehan** [nus-cs3281/2020#7]
## Summary
Dotfiles are plain text configuration files on Unux systems for things like our shell, ~/.zshrc, our editor in ~/.vimrc, and many others. They are called "dotfiles" as they typically are named with a leading . making them hidden files on your system, although this is not a strict requirement. This talk will delve into why you should take the time to properly configure your dotfiles

## PUNCH
- **Personal:** I used to not manage my dotfiles. I spent a lot of time typing long git commands, which was long and repetitive.

## WIIFY
- Managing your dotfiles properly can reduce overhead and improve your productivity.
- Using version control on your dotfiles allows you to reuse them on other systems and give you access to the features you customize.

## Promise/Road Map
- To appreciate the benefits of good dotfiles management

## Key Points
- Customizing dotfiles can provide features to simplify many things that you do
- Managing dotfiles with git allows you to easily port them over to other systems
- One will inevitably learn a lot (including highly employable skills) and have fun in the process of configuring dotfiles

## Impact
- **Know:** What dotfiles are and how they can be used to configure your system
- **Believe:** Customizing and managing your dotfiles can help become more productive, spend more time doing other things
- **Do:** Find out more about dotfiles

[Slides](https://docs.google.com/presentation/d/15ERYOaMNjS_uk1bos3Oh1pvVsGhazUfqwNuJll5kM4E/edit?usp=sharing)

**Comment by damithc** [comment]
Slides?

**Comment by tiuweehan** [comment]
@damithc it slipped my mind to link the slides, but I have added it in. Sorry for the delay!
